name: maneframe-desktop
channels:
- defaults
dependencies:
- libprotobuf=3.2.0=0
- mkl=2017.0.1=0
- numpy=1.12.1=py35_0
- openssl=1.0.2l=0
- pip=9.0.1=py35_1
- protobuf=3.2.0=py35_0
- python=3.5.2=0
- pyyaml=3.12=py35_0
- readline=6.2=2
- requests=2.14.2=py35_0
- setuptools=27.2.0=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tensorflow=1.1.0=np112py35_0
- tk=8.5.18=0
- werkzeug=0.12.2=py35_0
- wheel=0.29.0=py35_0
- xz=5.2.2=1
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - schedule==0.4.3
  - websockets==3.3
